---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: onsdigital/dp-concourse-tools-java

inputs:
  - name: resource-utils

outputs:
  - name: build

run:
  path: resource-utils/ci/scripts/build.sh
